### ISSUE TITLE
Circuit not updated after updating CDC

### ISSUE THREAD

**Issue by Aslan-Kosakian** [vyrjana/DearEIS#11]
**Desktop:**
- _DearEIS_ version 3.3.0
- Python version 3.8.10
- OS: Ubuntu 20.0

**Describe the bug**
When a CDC is edited in a window, parsed, and then accepted, the circuit graph in the main DearEIS window (Fitting or Simulation tab) is not updated. It is only updated after “Perform simulation” is clicked.

**To Reproduce**
1. Go to the "Fitting" tab and click "Edit" next to the CDC on the left.
2. Modify the CDC, click "Parse". Note the circuit diagram is updated in the "Circuit editor".
3. Click "Accept circuit".
4. Note that the circuit is not updated in the "Fitting" tab.
5. Click "Perform fit". The circuit diagram is updated now.

**Expected behavior**
The graphical representation of the circuit is expected to be automatically updated in step 4 instead of step 5.

**Comment by vyrjana** [comment]
It is working as intended. The `Circuit editor`  window shows what is being constructed while the `Fitting` tab shows the circuit that corresponds to the current result. Perhaps there should be a `Fitted circuit` label above the circuit in the `Fitting`  tab to make this clearer?

**Comment by vyrjana** [comment]
I've added labels above the circuit previews in the `Fitting` and `Simulation` tabs in [this commit](https://github.com/vyrjana/DearEIS/commit/9cbf0d6fc61df3a8fe0caea842975dc61abfe369).

**Comment by Aslan-Kosakian** [comment]
Ah, I got confused. A label will be helpful, thank you.
