### ISSUE TITLE
generate-api-reference.py missing api_documenter

### ISSUE THREAD

**Issue by Aslan-Kosakian** [vyrjana/DearEIS#7]
**Desktop (please complete the following information):**
- _DearEIS_ version 3.1.3
- Python version 3.8.10
- OS: Ubuntu 20.04

**Describe the bug**
If I try to run generate-api-reference.py (in docs), it complains that I don’t have api_documenter.
- This dependency needs to be indicated in the readme.
- This dependency needs to be automatically installed with DearEIS (pip install deareis).
- This dependency cannot be installed with pip. How do I install it?
- Am I supposed to run generate-api-reference.py at all? Its name suggests I am. What does it do?

**To Reproduce**
1. Go to 'DearEIS/docs/'
2. Run 'python3 generate-api-reference.py'

**Expected behavior**
Judging by the name, I expect the script to generate an API reference.

**Comment by vyrjana** [comment]
That script is used to generate the API documentation that is hosted as part of the project's GitHub pages (i.e., https://vyrjana.github.io/DearEIS/api). The same approach is used for the API documentation of the `pyimpspec` package that DearEIS is based on. Thus, to reduce code duplication, the `api_documenter` package contains the shared code and the script calls functions from that package.

The script is not intended to be executed by a typical end user of the program nor is it required for itself DearEIS to work. As a result, the `api_documenter` package is not available on PyPI and currently it is expected to be obtained separately from the [GitHub repository referenced](https://github.com/vyrjana/python-api-documenter) on line nr. 9 of `generate-api-reference.py`. The package can then be installed locally using by running the `pip install -e .` command from inside the cloned `api_documenter` repository.

I have not previously worked with Git submodules in any of my own projects but that might be a good solution. However, in that case I do need to figure out how to import the `api_documenter` package. It looks like I might need to either modify `sys.path` or use a symlink. I'm not sure if the latter would work as a platform independent solution.

**Comment by Aslan-Kosakian** [comment]
If users are not supposed to run generate-api-reference.py, why supply it with DearEIS? Perhaps it could be removed from the user version of the code to avoid confusion.

**Comment by vyrjana** [comment]
It is one of the development-related files just like, e.g., `build.sh`. Such files are not included in the distributions uploaded to PyPI, which is where most users would get DearEIS from.

**Comment by vyrjana** [comment]
I have [updated the documentation regarding how to get started with contributing code](https://github.com/vyrjana/DearEIS/commit/94aac5fad542085c509f9b28207cfa3ad1d52df7), [added the `api_documenter` dependency to the project as a Git submodule](https://github.com/vyrjana/DearEIS/commit/39e74cdfcdb44af7e550bf643bc6fc932a9df081), and [added a readme to the docs folder](https://github.com/vyrjana/DearEIS/commit/3fbdd6a5c909bd842004c10855f7bdb7b755c4cd).

**Comment by Aslan-Kosakian** [comment]
Thank you, this issue can be closed now.
